version: 2

builds:
  - id: japaya
    main: ./cmd/japaya
    binary: japaya
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  # Creates/updates the GitHub Release corresponding to the tag.
  draft: false
  prerelease: false

changelog:
  use: github
